#!/usr/bin/env bash

workspaces=(     )
w=0

gib_workspace_names() {
	wmctrl -d |
		awk '{ print $1 " " $2 " " $9 }' |
		grep -v NSP
}

gib_workspace_yuck() {
	buffered=""
	gib_workspace_names | while read -r id active name; do
		name="${name#*_}"
		if [ "$active" == '*' ]; then
			active_class="active"
		else
			active_class="inactive"
		fi

		if wmctrl -l | grep --regexp '.*\s\+'"$id"'\s\+.*' >/dev/null; then
			button_class="occupied"
			button_name="${workspaces[$w]}"
		else
			button_class="empty"
			button_name="${workspaces[$w]}"
		fi
		buffered+="(eventbox :cursor \"pointer\" (button :class \"$button_class-$active_class\"  :onclick \"wmctrl -s $id\" \"$button_name\"))"
		echo -n "$buffered"
		buffered=""
		((w = w + 1))
	done
}

box_attrs=':spacing 20 :class "workspaces" :space-evenly false :halign "center" :valign "center" :vexpand false '
xprop -spy -root _NET_CURRENT_DESKTOP | while read -r; do
	echo "(box $box_attrs $(gib_workspace_yuck))"
done
